name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies (Bypass package-lock.json)
        run: |
          rm package-lock.json
          npm install

      - name: Build website
        run: npm run build
